---
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: seeeduino_xiao_ble
    shield: totem_right
    #snippet: zmk-usb-logging
