draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: true
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  svg_extra_style: |
    /* For default sytles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */

    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held {
        fill: #ffc;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Layer taps
    "&layer_tap 6 DELETE":
      tap: $$mdi:backspace-reverse-outline$$
      hold: 'GAMING'
    "&layer_tap 5 ESC":
      tap: $$mdi:keyboard-esc$$
      hold: 'SYSTEM'
    "&layer_tap 4 BACKSPACE":
      tap: $$mdi:backspace$$
      hold: 'NUMBER'
    "&layer_tap 3 SPACE":
      tap: $$mdi:keyboard-space$$
      hold: 'SYMBOL'
    "&layer_tap 5 ENTER":
      tap: $$mdi:keyboard-return$$
      hold: 'SYSTEM'
    "&layer_tap 7 TAB":
      tap: $$mdi:keyboard-tab$$
      hold: 'LOWER'

    # Home row mods - left (QWERTY)
    "&hrm_left LGUI A":
      tap: 'A'
      shifted: $$mdi:apple-keyboard-command$$
    "&hrm_left LALT S":
      tap: 'S'
      shifted: $$mdi:apple-keyboard-option$$
    "&hrm_left LCTRL D":
      tap: 'D'
      shifted: $$mdi:apple-keyboard-control$$
    "&hrm_left LSHFT F":
      tap: 'F'
      shifted: $$mdi:apple-keyboard-shift$$
    # Colemak left
    "&hrm_left LALT R":
      tap: 'R'
      shifted: $$mdi:apple-keyboard-option$$
    "&hrm_left LCTRL S":
      tap: 'S'
      shifted: $$mdi:apple-keyboard-control$$
    "&hrm_left LSHFT T":
      tap: 'T'
      shifted: $$mdi:apple-keyboard-shift$$
    # Engram left
    "&hrm_left LGUI C":
      tap: 'C'
      shifted: $$mdi:apple-keyboard-command$$
    "&hrm_left LALT I":
      tap: 'I'
      shifted: $$mdi:apple-keyboard-option$$
    "&hrm_left LCTRL E":
      tap: 'E'
      shifted: $$mdi:apple-keyboard-control$$
    "&hrm_left LSHFT A":
      tap: 'A'
      shifted: $$mdi:apple-keyboard-shift$$

    # Home row mods - right (QWERTY)
    "&hrm_right RSHFT J":
      tap: 'J'
      shifted: $$mdi:apple-keyboard-shift$$
    "&hrm_right RCTRL K":
      tap: 'K'
      shifted: $$mdi:apple-keyboard-control$$
    "&hrm_right RALT L":
      tap: 'L'
      shifted: $$mdi:apple-keyboard-option$$
    "&hrm_right RGUI SEMI":
      tap: ';'
      shifted: $$mdi:apple-keyboard-command$$
    # Colemak/Engram right
    "&hrm_right RSHFT N":
      tap: 'N'
      shifted: $$mdi:apple-keyboard-shift$$
    "&hrm_right RCTRL E":
      tap: 'E'
      shifted: $$mdi:apple-keyboard-control$$
    "&hrm_right RALT I":
      tap: 'I'
      shifted: $$mdi:apple-keyboard-option$$
    "&hrm_right RGUI O":
      tap: 'O'
      shifted: $$mdi:apple-keyboard-command$$
    # Engram right
    "&hrm_right RSHFT H":
      tap: 'H'
      shifted: $$mdi:apple-keyboard-shift$$
    "&hrm_right RCTRL T":
      tap: 'T'
      shifted: $$mdi:apple-keyboard-control$$
    "&hrm_right RALT S":
      tap: 'S'
      shifted: $$mdi:apple-keyboard-option$$
    "&hrm_right RGUI N":
      tap: 'N'
      shifted: $$mdi:apple-keyboard-command$$

    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Bluetooth
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-up-bold$$
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-down-bold$$
    "&bt BT_CLR":
      tap: $$mdi:bluetooth-off$$
    "&bt BT_CLR_ALL":
      tap: $$mdi:bluetooth-off$$
      hold: ALL

    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: <
    LT: <
    PERIOD: '.'
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:apple-keyboard-command$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$
    RIGHT_GUI: $$mdi:apple-keyboard-command$$
    PSCRN: $$mdi:printer-outline$$
    PRINTSCREEN: $$mdi:printer-outline$$
    PAGE_UP:
      tap: 'PgUp'
    PAGE_DOWN:
      tap: 'PgDn'
    PG_UP:
      tap: 'PgUp'
    PG_DN:
      tap: 'PgDn'
    HOME: $$mdi:page-first$$
    END: $$mdi:page-last$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$
    K_LOCK: $$mdi:lock$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$
    C_PLAY_PAUSE: $$mdi:play-pause$$
    C_FF: $$mdi:fast-forward$$
    C_RW: $$mdi:rewind$$

    # Edit operations
    K_UNDO: $$mdi:undo$$
    K_REDO: $$mdi:redo$$
    K_CUT: $$mdi:content-cut$$
    K_COPY: $$mdi:content-copy$$
    K_PASTE: $$mdi:content-paste$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

  zmk_combos:
    combo_esc:
      align: top
